### ISSUE TITLE
Shared stash does not hold items after save and exit.

### ISSUE THREAD

**Issue by rupturre5** [shalzuth/D2RModding#11]
Shared stash does not hold items after save and exit.

Tested a few times ; normal stash does hot them  ; the shared stash erases the items every time ( i used the v 1.08 to test it ) .

**Comment by shalzuth** [comment]
In TCP/IP or singleplayer?

**Comment by rupturre5** [comment]
> In TCP/IP or singleplayer?

TCP/IP , in 1.08 the Singleplayer did not work ... getting a black screen  ; in 1.10 it works .

**Comment by PlanK69** [comment]
I have 1.11 and my shared stash disappeared completely when i used 'host tcp/ip', but my shared stash is intact when using 'play game'. So it seems that 'host tcp/ip' erases the shard stash each time and can't save items anymore.

On a side note, I have lost a few characters (their save files are still in my saved games file, but they don't appear in-game). I'm still investigating what the cause is, by switching between ver 1.01-1.11 and trying each version.

**Comment by PlanK69** [comment]
OK so I found out how I lost the characters... If you start a game with a character using 'host tcp/ip' and then at any point during the gameplay you alt+f4, the character then will no longer show up in the character list when you start the game up again... I don't know what causes this, or why it's only if you alt+f4 during 'host tcp/ip' and the same doesn't happen if you alt+f4 during 'singleplayer'.... all I know is I have now lost a couple of character due to this testing and though I still have their save files, I no longer can see them in my game. See if you can replicate the 'character deletion' and then also see if you can't get the character to show up again in the in-game selection menu.

**Comment by rupturre5** [comment]
> OK so I found out how I lost the characters... If you start a game with a character using 'host tcp/ip' and then at any point during the gameplay you alt+f4, the character then will no longer show up in the character list when you start the game up again... I don't know what causes this, or why it's only if you alt+f4 during 'host tcp/ip' and the same doesn't happen if you alt+f4 during 'singleplayer'.... all I know is I have now lost a couple of character due to this testing and though I still have their save files, I no longer can see them in my game. See if you can replicate the 'character deletion' and then also see if you can't get the character to show up again in the in-game selection menu (although, it seems that when you alt+f4 during 'host tcp/ip' that the .d2s file of your character is then completely wiped clean for some infuriating reason, so recovery of those characters are probably impossible now).

try getting them back via recuva it is a free util .

**Comment by shalzuth** [comment]
tcp/ip doesn't support shared stash
